### ISSUE TITLE
Pin It! is not compatible with autoupdating apps such as Beeper

### ISSUE THREAD

**Issue by Netherquark** [ryonakano/pinit#103]
I use Pin It! to get a Gnome desktop entry for the [Beeper](https://www.beeper.com/) AppImage.

Location of the AppImage:

![image](https://github.com/ryonakano/pinit/assets/65618735/67cb053e-5f16-4b7f-b477-b281c43aedcb)

Pin It! configuration for Beeper:

![image](https://github.com/ryonakano/pinit/assets/65618735/2251710e-74f3-44b9-9c96-d55fd84b5fc8)

Beeper has a self updating system, where the name of the AppImage changes in the following format: `beeper-3.63.16.AppImage` > `beeper-3.63.20.AppImage`. Due to this, I have to update the Pin It! entry every time I get a Beeper update. This is inconvenient. I tried adding an asterisk (*) as a wildcard after beeper in the form of `beeper-*.AppImage`, however this did not work. Please suggest a way to get this issue solved.

**Comment by ryonakano** [comment]
> I tried adding an asterisk (*) as a wildcard after beeper in the form of `beeper-*.AppImage`, however this did not work.

The desktop file created by Pin It! follows the [Desktop Entry Specification by freedesktop.org](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), and it does not support including `*` to specify the executable. This is why it didn't work.

However, you should resolve this issue by creating a wrapper script like this:

```bash
ryo@lb450m:~/Documents$ cat beeper.sh 
#!/bin/bash

eval $(find ~/Documents/ -name "beeper-*.AppImage" | head -n1)
ryo@lb450m:~/Documents$ 
```

And specify the script above instead of specifying the AppImage:

![スクリーンショット 2023-07-12 23 36 04](https://github.com/ryonakano/pinit/assets/26003928/f5eade68-fb8a-41f5-82ce-036125725047)

**Comment by Netherquark** [comment]
That worked excellently! Thank you so much.
