### ISSUE TITLE
Use org.freedesktop.portal.DynamicLauncher instead of home rw access

### ISSUE THREAD

**Issue by sandorex** [ryonakano/pinit#189]
Is there any reason the app is not using the [DynamicLauncher portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.DynamicLauncher.html)

I am one of the bit paranoid users so it would soothe me and possibly others as the app would probably lose the `potentionally unsafe` marking on flathub

**Comment by ryonakano** [comment]
Thank you for your info, I didn't know the existence of that API. I'll take a look at it.

**Comment by ryonakano** [comment]
Note to myself:

- https://valadoc.org/libportal/Xdp.Portal.dynamic_launcher_prepare_install.html
- https://valadoc.org/libportal/Xdp.Portal.dynamic_launcher_install.html

**Comment by ryonakano** [comment]
OK so after investigation I found we can't use these APIs, because these APIs aim to register desktop entries **that runs on the caller application** as written in the doc:

> The DynamicLauncher portal allows sandboxed (or unsandboxed) applications to install launchers (.desktop files) which have an icon associated with them and which execute a command in the application.

which means the Exec line looks like this if you register gnome-software for example:

```
[Desktop Entry]
GenericName=Demo App
Comment=Demonstrate libportal dynamic launcher module
Categories=GTK;Utility;
Exec=flatpak run --command=gnome-software 'io.github.ryonakano.portal-dynamic-launcher-demo'
Type=Application
Name=Portal Dynamic Launcher Demo
Icon=/home/ryo/.local/share/xdg-desktop-portal/icons/scalable/io.github.ryonakano.portal-dynamic-launcher-demo.example.svg
TryExec=/home/ryo/.local/share/flatpak/exports/bin/io.github.ryonakano.portal-dynamic-launcher-demo
X-Flatpak=io.github.ryonakano.portal-dynamic-launcher-demo
```

We want to handle independent desktop entries in Pin It!, so these APIs are not for our usage.
Closing as "Won't Fix", but thank you for your idea anyways :+1:
