### ISSUE TITLE
Program uses different directory when browsing path of executable

### ISSUE THREAD

**Issue by Nikko-A** [ryonakano/pinit#61]
I have an issue where if I browse to the path of my program, which in this case is in the `/home/<folder>` directory, it instead uses the `/run/user/` directory. I don't know if this was intended behavior, system error or program error so some insight would be much appreciated. I like using this program since it saves me a lot of headaches, so to have this issue solved would be a life-changer.
 
Information:
1. OS is Fedora 36 Workstation Beta
2. Application was installed through flathub

**Comment by ryonakano** [comment]
Thank you for using my app and reporting this issue! I'm glad my app helps your productivity.

Regarding to the wrong directory being shown, I guess it's because the app runs in the sandboxed environment (Flatpak). Maybe the app accesses the icons or executables through some interface provided by Flatpak and the results of that may be this.

Maybe we can add a code to replace the '/run/usr/...' to '/home/username/'? I will dig into this in a few days.

**Comment by Nikko-A** [comment]
That is extremely appreciated! Once again, thank you for creating this program. I even with what I've experience, it's still an incredibly wonderful program.

**Comment by ryonakano** [comment]
Now I decided to revert the changes I made intended to fix this issue previously because in that way any pathes in the home dir are shown as expected, but it don't work for other pathes (like pathes into other disks). We should not give permission to all dirs only in order to show the path correctly.

Re-opening the issue to seek for another way to show pathes correctly.

**Comment by SRNissen** [comment]
Quite possibly the answer is that `Pin It!` shouldn't be a sandboxed flatpak to begin with? It's a systems utility, it needs access to the system.

But on the off chance you have't seen it before (I'm sure you've seen it before but just on the off chance you haven't) there is:

https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access
