### ISSUE TITLE
After the update to Fedora 36, the icon of pinned apps in the launcher won't be shown even if reinstalled

### ISSUE THREAD

**Issue by alqikaramano** [ryonakano/pinit#64]
I've just updated to fedora 36 / GNOME 42.1 and i 'm having the following issue which it was not existing in the previous versions of fedora.

**issue**

1. the icon of pinned apps (appimage) in the launcher has disappeared after the update to fedora 36 
2. I've reinstalled "Pin it" several times and as a result the icon of pinned apps have bean appeared each time but after the restarting of my laptop the same issue reappears

**Comment by ryonakano** [comment]
Hi, thank you for your reporting!

I guess this is a temporary issue due to the system of sandboxing. Because "Pin It!" is sandboxed using Flatpak, we can't get direct access to the icons you specified in the file chooser in the app.

Would you check if this issue is fixed when you re-select icons you specified in "Pin It!"?

**Comment by alqikaramano** [comment]
When i start my laptop i see this on launcher

![Screenshot from 2022-05-29 18-44-55](https://user-images.githubusercontent.com/105975801/170878548-8aae0998-a3d1-46dc-8b1c-ac9079e6a34f.png)

Then, to show up the missing pinned icons by "Pin it" i follow the some procedure every time after the start up of my system:

I go to entries

![Screenshot from 2022-05-29 18-45-25](https://user-images.githubusercontent.com/105975801/170878565-d0ace5c9-f30a-465f-88ce-fdc84e0ffaa3.png)

and push the save button without change anything.

![Screenshot from 2022-05-29 18-45-36](https://user-images.githubusercontent.com/105975801/170878584-8db4b13d-789c-433e

finally, the missing icons come the launcher again.

![Screenshot from 2022-05-29 18-45-54](https://user-images.githubusercontent.com/105975801/170878669-33689ac2-8f25-49bf-a4cf-2aea8723d19f.png)

**Comment by ryonakano** [comment]
Hi, thank you for sharing detailed information and sorry for your inconvenience.

What would happen if you give read/write permission to your home directory to "Pin It!" (e.g. by using some tool like [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal))?

![screenshot](https://user-images.githubusercontent.com/26003928/171618561-f2760950-03f0-425f-b7cd-500931361a26.png)

(Turn on the switch enclosed in the above screenshot)

**Comment by charles-marceau** [comment]
Hi, I had the same problem on Fedora 37 beta and giving Pin It access to my appimages & their icons as @ryonakano suggested fixed the problem.

However, I always prefer giving just enough access to applications, so I only gave it access to my appimage directory instead of all user files.

Thank you!
